// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./llmkit.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('llmkit-node-android-arm64')
        const bindingPackageVersion = require('llmkit-node-android-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./llmkit.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('llmkit-node-android-arm-eabi')
        const bindingPackageVersion = require('llmkit-node-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if (process.config?.variables?.shlib_suffix === 'dll.a' || process.config?.variables?.node_target_type === 'shared_library') {
        try {
        return require('./llmkit.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('llmkit-node-win32-x64-gnu')
        const bindingPackageVersion = require('llmkit-node-win32-x64-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./llmkit.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('llmkit-node-win32-x64-msvc')
        const bindingPackageVersion = require('llmkit-node-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./llmkit.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('llmkit-node-win32-ia32-msvc')
        const bindingPackageVersion = require('llmkit-node-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./llmkit.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('llmkit-node-win32-arm64-msvc')
        const bindingPackageVersion = require('llmkit-node-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./llmkit.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('llmkit-node-darwin-universal')
      const bindingPackageVersion = require('llmkit-node-darwin-universal/package.json').version
      if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./llmkit.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('llmkit-node-darwin-x64')
        const bindingPackageVersion = require('llmkit-node-darwin-x64/package.json').version
        if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./llmkit.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('llmkit-node-darwin-arm64')
        const bindingPackageVersion = require('llmkit-node-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./llmkit.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('llmkit-node-freebsd-x64')
        const bindingPackageVersion = require('llmkit-node-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./llmkit.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('llmkit-node-freebsd-arm64')
        const bindingPackageVersion = require('llmkit-node-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./llmkit.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('llmkit-node-linux-x64-musl')
          const bindingPackageVersion = require('llmkit-node-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./llmkit.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('llmkit-node-linux-x64-gnu')
          const bindingPackageVersion = require('llmkit-node-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./llmkit.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('llmkit-node-linux-arm64-musl')
          const bindingPackageVersion = require('llmkit-node-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./llmkit.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('llmkit-node-linux-arm64-gnu')
          const bindingPackageVersion = require('llmkit-node-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./llmkit.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('llmkit-node-linux-arm-musleabihf')
          const bindingPackageVersion = require('llmkit-node-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./llmkit.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('llmkit-node-linux-arm-gnueabihf')
          const bindingPackageVersion = require('llmkit-node-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./llmkit.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('llmkit-node-linux-loong64-musl')
          const bindingPackageVersion = require('llmkit-node-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./llmkit.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('llmkit-node-linux-loong64-gnu')
          const bindingPackageVersion = require('llmkit-node-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./llmkit.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('llmkit-node-linux-riscv64-musl')
          const bindingPackageVersion = require('llmkit-node-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./llmkit.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('llmkit-node-linux-riscv64-gnu')
          const bindingPackageVersion = require('llmkit-node-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./llmkit.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('llmkit-node-linux-ppc64-gnu')
        const bindingPackageVersion = require('llmkit-node-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./llmkit.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('llmkit-node-linux-s390x-gnu')
        const bindingPackageVersion = require('llmkit-node-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./llmkit.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('llmkit-node-openharmony-arm64')
        const bindingPackageVersion = require('llmkit-node-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./llmkit.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('llmkit-node-openharmony-x64')
        const bindingPackageVersion = require('llmkit-node-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./llmkit.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('llmkit-node-openharmony-arm')
        const bindingPackageVersion = require('llmkit-node-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '0.1.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./llmkit.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
    try {
      wasiBinding = require('llmkit-node-wasm32-wasi')
      nativeBinding = wasiBinding
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        if (!wasiBindingError) {
          wasiBindingError = err
        } else {
          wasiBindingError.cause = err
        }
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err
          return cur
        }),
      },
    )
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.JsAsyncStreamIterator = nativeBinding.JsAsyncStreamIterator
module.exports.JsBatchError = nativeBinding.JsBatchError
module.exports.JsBatchJob = nativeBinding.JsBatchJob
module.exports.JsBatchRequest = nativeBinding.JsBatchRequest
module.exports.JsBatchRequestCounts = nativeBinding.JsBatchRequestCounts
module.exports.JsBatchResult = nativeBinding.JsBatchResult
module.exports.JsCacheBreakpoint = nativeBinding.JsCacheBreakpoint
module.exports.JsClassificationRequest = nativeBinding.JsClassificationRequest
module.exports.JsClientBuilder = nativeBinding.JsClientBuilder
module.exports.JsCompletionRequest = nativeBinding.JsCompletionRequest
module.exports.JsCompletionResponse = nativeBinding.JsCompletionResponse
module.exports.JsContentBlock = nativeBinding.JsContentBlock
module.exports.JsContentDelta = nativeBinding.JsContentDelta
module.exports.JsEmbedding = nativeBinding.JsEmbedding
module.exports.JsEmbeddingRequest = nativeBinding.JsEmbeddingRequest
module.exports.JsEmbeddingResponse = nativeBinding.JsEmbeddingResponse
module.exports.JsEmbeddingUsage = nativeBinding.JsEmbeddingUsage
module.exports.JsGeneratedImage = nativeBinding.JsGeneratedImage
module.exports.JsImageGenerationRequest = nativeBinding.JsImageGenerationRequest
module.exports.JsLLMKitClient = nativeBinding.JsLLMKitClient
module.exports.JsMessage = nativeBinding.JsMessage
module.exports.JsModelInfo = nativeBinding.JsModelInfo
module.exports.JsModerationRequest = nativeBinding.JsModerationRequest
module.exports.JsRankedDocument = nativeBinding.JsRankedDocument
module.exports.JsRankingRequest = nativeBinding.JsRankingRequest
module.exports.JsRealtimeProvider = nativeBinding.JsRealtimeProvider
module.exports.JsRealtimeSession = nativeBinding.JsRealtimeSession
module.exports.JsRerankedResult = nativeBinding.JsRerankedResult
module.exports.JsRerankingRequest = nativeBinding.JsRerankingRequest
module.exports.JsRetryConfig = nativeBinding.JsRetryConfig
module.exports.JsStreamChunk = nativeBinding.JsStreamChunk
module.exports.JsStructuredOutput = nativeBinding.JsStructuredOutput
module.exports.JsSynthesisRequest = nativeBinding.JsSynthesisRequest
module.exports.JsThinkingConfig = nativeBinding.JsThinkingConfig
module.exports.JsTokenCountRequest = nativeBinding.JsTokenCountRequest
module.exports.JsTokenCountResult = nativeBinding.JsTokenCountResult
module.exports.JsToolBuilder = nativeBinding.JsToolBuilder
module.exports.JsToolDefinition = nativeBinding.JsToolDefinition
module.exports.JsTranscribeOptions = nativeBinding.JsTranscribeOptions
module.exports.JsTranscriptionConfig = nativeBinding.JsTranscriptionConfig
module.exports.JsTranscriptionRequest = nativeBinding.JsTranscriptionRequest
module.exports.JsUsage = nativeBinding.JsUsage
module.exports.JsVadConfig = nativeBinding.JsVadConfig
module.exports.JsVideoGenerationOptions = nativeBinding.JsVideoGenerationOptions
module.exports.JsVideoGenerationRequest = nativeBinding.JsVideoGenerationRequest
module.exports.JsVideoGenerationResponse = nativeBinding.JsVideoGenerationResponse
module.exports.getAllModels = nativeBinding.getAllModels
module.exports.getAvailableModels = nativeBinding.getAvailableModels
module.exports.getCheapestModel = nativeBinding.getCheapestModel
module.exports.getClassifierModels = nativeBinding.getClassifierModels
module.exports.getCurrentModels = nativeBinding.getCurrentModels
module.exports.getModelInfo = nativeBinding.getModelInfo
module.exports.getModelsByProvider = nativeBinding.getModelsByProvider
module.exports.getModelsWithCapability = nativeBinding.getModelsWithCapability
module.exports.getRegistryStats = nativeBinding.getRegistryStats
module.exports.JsAudioLanguage = nativeBinding.JsAudioLanguage
module.exports.JsBatchStatus = nativeBinding.JsBatchStatus
module.exports.JsCacheControl = nativeBinding.JsCacheControl
module.exports.JsDeepgramVersion = nativeBinding.JsDeepgramVersion
module.exports.JsEmbeddingInputType = nativeBinding.JsEmbeddingInputType
module.exports.JsEncodingFormat = nativeBinding.JsEncodingFormat
module.exports.JsImageFormat = nativeBinding.JsImageFormat
module.exports.JsImageQuality = nativeBinding.JsImageQuality
module.exports.JsImageSize = nativeBinding.JsImageSize
module.exports.JsImageStyle = nativeBinding.JsImageStyle
module.exports.JsLatencyMode = nativeBinding.JsLatencyMode
module.exports.JsModelStatus = nativeBinding.JsModelStatus
module.exports.JsProvider = nativeBinding.JsProvider
module.exports.JsRole = nativeBinding.JsRole
module.exports.JsStopReason = nativeBinding.JsStopReason
module.exports.JsStreamEventType = nativeBinding.JsStreamEventType
module.exports.JsThinkingEffort = nativeBinding.JsThinkingEffort
module.exports.JsThinkingType = nativeBinding.JsThinkingType
module.exports.JsVideoModel = nativeBinding.JsVideoModel
module.exports.listProviders = nativeBinding.listProviders
module.exports.supportsStructuredOutput = nativeBinding.supportsStructuredOutput
