/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'llmkit.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./llmkit.android-arm64.node')
          } else {
            nativeBinding = require('llmkit-node-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'llmkit.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./llmkit.android-arm-eabi.node')
          } else {
            nativeBinding = require('llmkit-node-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'llmkit.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./llmkit.win32-x64-msvc.node')
          } else {
            nativeBinding = require('llmkit-node-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'llmkit.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./llmkit.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('llmkit-node-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'llmkit.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./llmkit.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('llmkit-node-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'llmkit.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./llmkit.darwin-universal.node')
      } else {
        nativeBinding = require('llmkit-node-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'llmkit.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./llmkit.darwin-x64.node')
          } else {
            nativeBinding = require('llmkit-node-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'llmkit.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./llmkit.darwin-arm64.node')
          } else {
            nativeBinding = require('llmkit-node-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'llmkit.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./llmkit.freebsd-x64.node')
      } else {
        nativeBinding = require('llmkit-node-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'llmkit.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./llmkit.linux-x64-musl.node')
            } else {
              nativeBinding = require('llmkit-node-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'llmkit.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./llmkit.linux-x64-gnu.node')
            } else {
              nativeBinding = require('llmkit-node-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'llmkit.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./llmkit.linux-arm64-musl.node')
            } else {
              nativeBinding = require('llmkit-node-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'llmkit.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./llmkit.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('llmkit-node-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'llmkit.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./llmkit.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('llmkit-node-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'llmkit.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./llmkit.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('llmkit-node-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'llmkit.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./llmkit.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('llmkit-node-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'llmkit.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./llmkit.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('llmkit-node-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'llmkit.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./llmkit.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('llmkit-node-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { JsDeepgramVersion, JsTranscribeOptions, JsLatencyMode, JsSynthesizeOptions, JsAudioLanguage, JsTranscriptionConfig, JsTranscriptionRequest, JsSynthesisRequest, JsLLMKitClient, JsClientBuilder, JsImageSize, JsImageQuality, JsImageStyle, JsImageFormat, JsImageGenerationRequest, JsGeneratedImage, JsProvider, JsModelStatus, JsModelInfo, getModelInfo, getAllModels, getModelsByProvider, getCurrentModels, getClassifierModels, getAvailableModels, getModelsWithCapability, getCheapestModel, supportsStructuredOutput, getRegistryStats, listProviders, JsVadConfig, JsSessionConfig, JsRealtimeSession, JsRealtimeProvider, JsRetryConfig, JsRankingRequest, JsRankedDocument, JsRerankingRequest, JsRerankedResult, JsModerationRequest, JsModerationResponse, JsClassificationRequest, JsToolDefinition, JsToolBuilder, JsEncodingFormat, JsEmbeddingInputType, JsEmbeddingRequest, JsEmbedding, JsEmbeddingUsage, JsEmbeddingResponse, JsRole, JsStopReason, JsStreamEventType, JsCacheControl, JsThinkingType, JsThinkingEffort, JsBatchStatus, JsContentBlock, JsMessage, JsCacheBreakpoint, JsThinkingConfig, JsStructuredOutput, JsCompletionRequest, JsTokenCountRequest, JsBatchRequest, JsBatchRequestCounts, JsBatchJob, JsBatchError, JsBatchResult, JsTokenCountResult, JsUsage, JsCompletionResponse, JsContentDelta, JsStreamChunk, JsAsyncStreamIterator, JsVideoModel, JsVideoGenerationOptions, JsVideoGenerationResponse, JsVideoGenerationRequest } = nativeBinding

module.exports.JsDeepgramVersion = JsDeepgramVersion
module.exports.JsTranscribeOptions = JsTranscribeOptions
module.exports.JsLatencyMode = JsLatencyMode
module.exports.JsSynthesizeOptions = JsSynthesizeOptions
module.exports.JsAudioLanguage = JsAudioLanguage
module.exports.JsTranscriptionConfig = JsTranscriptionConfig
module.exports.JsTranscriptionRequest = JsTranscriptionRequest
module.exports.JsSynthesisRequest = JsSynthesisRequest
module.exports.JsLLMKitClient = JsLLMKitClient
module.exports.JsClientBuilder = JsClientBuilder
module.exports.JsImageSize = JsImageSize
module.exports.JsImageQuality = JsImageQuality
module.exports.JsImageStyle = JsImageStyle
module.exports.JsImageFormat = JsImageFormat
module.exports.JsImageGenerationRequest = JsImageGenerationRequest
module.exports.JsGeneratedImage = JsGeneratedImage
module.exports.JsProvider = JsProvider
module.exports.JsModelStatus = JsModelStatus
module.exports.JsModelInfo = JsModelInfo
module.exports.getModelInfo = getModelInfo
module.exports.getAllModels = getAllModels
module.exports.getModelsByProvider = getModelsByProvider
module.exports.getCurrentModels = getCurrentModels
module.exports.getClassifierModels = getClassifierModels
module.exports.getAvailableModels = getAvailableModels
module.exports.getModelsWithCapability = getModelsWithCapability
module.exports.getCheapestModel = getCheapestModel
module.exports.supportsStructuredOutput = supportsStructuredOutput
module.exports.getRegistryStats = getRegistryStats
module.exports.listProviders = listProviders
module.exports.JsVadConfig = JsVadConfig
module.exports.JsSessionConfig = JsSessionConfig
module.exports.JsRealtimeSession = JsRealtimeSession
module.exports.JsRealtimeProvider = JsRealtimeProvider
module.exports.JsRetryConfig = JsRetryConfig
module.exports.JsRankingRequest = JsRankingRequest
module.exports.JsRankedDocument = JsRankedDocument
module.exports.JsRerankingRequest = JsRerankingRequest
module.exports.JsRerankedResult = JsRerankedResult
module.exports.JsModerationRequest = JsModerationRequest
module.exports.JsModerationResponse = JsModerationResponse
module.exports.JsClassificationRequest = JsClassificationRequest
module.exports.JsToolDefinition = JsToolDefinition
module.exports.JsToolBuilder = JsToolBuilder
module.exports.JsEncodingFormat = JsEncodingFormat
module.exports.JsEmbeddingInputType = JsEmbeddingInputType
module.exports.JsEmbeddingRequest = JsEmbeddingRequest
module.exports.JsEmbedding = JsEmbedding
module.exports.JsEmbeddingUsage = JsEmbeddingUsage
module.exports.JsEmbeddingResponse = JsEmbeddingResponse
module.exports.JsRole = JsRole
module.exports.JsStopReason = JsStopReason
module.exports.JsStreamEventType = JsStreamEventType
module.exports.JsCacheControl = JsCacheControl
module.exports.JsThinkingType = JsThinkingType
module.exports.JsThinkingEffort = JsThinkingEffort
module.exports.JsBatchStatus = JsBatchStatus
module.exports.JsContentBlock = JsContentBlock
module.exports.JsMessage = JsMessage
module.exports.JsCacheBreakpoint = JsCacheBreakpoint
module.exports.JsThinkingConfig = JsThinkingConfig
module.exports.JsStructuredOutput = JsStructuredOutput
module.exports.JsCompletionRequest = JsCompletionRequest
module.exports.JsTokenCountRequest = JsTokenCountRequest
module.exports.JsBatchRequest = JsBatchRequest
module.exports.JsBatchRequestCounts = JsBatchRequestCounts
module.exports.JsBatchJob = JsBatchJob
module.exports.JsBatchError = JsBatchError
module.exports.JsBatchResult = JsBatchResult
module.exports.JsTokenCountResult = JsTokenCountResult
module.exports.JsUsage = JsUsage
module.exports.JsCompletionResponse = JsCompletionResponse
module.exports.JsContentDelta = JsContentDelta
module.exports.JsStreamChunk = JsStreamChunk
module.exports.JsAsyncStreamIterator = JsAsyncStreamIterator
module.exports.JsVideoModel = JsVideoModel
module.exports.JsVideoGenerationOptions = JsVideoGenerationOptions
module.exports.JsVideoGenerationResponse = JsVideoGenerationResponse
module.exports.JsVideoGenerationRequest = JsVideoGenerationRequest
