name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: Another approach could be...
    validations:
      required: false

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area does this feature relate to?
      options:
        - New Provider Support
        - Existing Provider Enhancement
        - Streaming
        - Tool Calling
        - Embeddings
        - Extended Thinking
        - Audio/Voice APIs
        - Video Generation
        - Image Generation
        - Python Bindings
        - Node.js Bindings
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case for this feature
      placeholder: I need this feature because...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Usage (Optional)
      description: Show how you envision using this feature
      render: rust
      placeholder: |
        // Example of how the API might look
        let client = LLMKitClient::from_env()?;
        client.new_feature(...).await?;
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or links about the feature request
      placeholder: Additional information...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have provided a clear description of the feature
          required: true
        - label: I am willing to contribute to the implementation (optional)
          required: false
